#!/usr/bin/env python3
import os
import json
import urllib.request
import subprocess

def main():
    kimi_key = os.environ['KIMI_API_KEY']
    github_token = os.environ['GITHUB_TOKEN']
    pr_number = os.environ['PR_NUMBER']
    repo = os.environ['REPO']
    base_ref = os.environ['BASE_REF']

    subprocess.run(['git', 'fetch', 'origin', base_ref], check=True)
    result = subprocess.run(
        ['git', 'diff', f'origin/{base_ref}..HEAD'],
        capture_output=True, text=True
    )
    diff = result.stdout[:12000]

    payload = {
        "model": "kimi-k2",
        "messages": [
            {
                "role": "system",
                "content": """你是一个专业的代码审查助手。请分析代码变更，提供双语报告：

## 中文审查报告

**变更总结**: (简述做了什么改动)
**问题与建议**: (列出潜在问题或改进建议)
**代码评分**: X/5

---

## English Review Report

**Summary**: (Description of changes)
**Issues & Suggestions**: (List of issues/improvements)
**Rating**: X/5 stars"""
            },
            {
                "role": "user",
                "content": f"Please review this code diff:\n\n{diff}"
            }
        ]
    }

    req = urllib.request.Request(
        'https://api.moonshot.cn/v1/chat/completions',
        data=json.dumps(payload).encode('utf-8'),
        headers={'Authorization': f'Bearer {kimi_key}', 'Content-Type': 'application/json'}
    )

    with urllib.request.urlopen(req) as resp:
        result = json.loads(resp.read().decode('utf-8'))
        review = result['choices'][0]['message']['content']

    comment = {"body": f"## 🤖 Kimi Code Review Report\n\n{review}\n\n---\n*Generated by Kimi AI*"}
    
    req2 = urllib.request.Request(
        f'https://api.github.com/repos/{repo}/issues/{pr_number}/comments',
        data=json.dumps(comment).encode('utf-8'),
        headers={'Authorization': f'token {github_token}', 'Accept': 'application/vnd.github.v3+json'}
    )

    with urllib.request.urlopen(req2):
        print("Done!")

if __name__ == '__main__':
    main()
